insert into [dbo].[ContactPersons] (Name, Email, Employer_Id)
values('Jan Splinter', 'jsplinter@bar.com', 1)
,('Mieke van Oordrecht', 'mieke@foobar.com', 2)
,('Joost van der Gondel', 'jvg@bar.com', 3)
,('Thijs Visser', 'thijs@fb.com', 4)
,('Jeffrey van ''t Gooi', 'gooi@foobar.com', 5)
,('Laura Waterweg', 'lw@barfoo.com', 6)
,('Danielle Hoeverink', 'dh@barfoo@bar.com', 7)
,('Jantine Boer', 'boer@foob@barf.com', 8)