insert into Employers (Name, LogoFilename, Description, Zipcode) 
VALUES ('Adidas', '', 'Ontwerpen en verkopen sportschoenen wereldwijd', '3363JD')
,('Niks', '', 'Air max is een veel gedragen sportschoen', '3362HB')
,('Coca Cola', '', 'Lekkere zwarte chemische meuk met prik', '4205XP')
,('Fanta', '', 'Lekkere sinaasappel frisdrank met koolzuur', '9121CB')
,('7-UP', '', 'Ga niet naar Sprite, ga hoger en kom bij 7-up', '3365DB')
,('De Heer Software', '', 'Affiniteit met de zorg en sofwtare ontwikkeling. Help mee met de bouw van PCD en PCK', '3362TV')
,('Quality Equipment', '', 'Leuk jong bedrijf met frisse mensen en een leuk softwarepakket genaamd Q-7', '2984CD')
,('Dazzleware', '', 'Klein knus bedrijf dat software op maat levert', '1066EP')