insert into ThinkLevels (Name)
values ('MBO'), ('HBO'), ('WO')

insert into Employers (Name, LogoFilename, Description, Zipcode) 
VALUES ('Adidas', '', 'Ontwerpen en verkopen sportschoenen wereldwijd', '3363JD')
,('Niks', '', 'Air max is een veel gedragen sportschoen', '3362HB')
,('Coca Cola', '', 'Lekkere zwarte chemische meuk met prik', '4205XP')
,('Fanta', '', 'Lekkere sinaasappel frisdrank met koolzuur', '9121CB')
,('7-UP', '', 'Ga niet naar Sprite, ga hoger en kom bij 7-up', '3365DB')
,('De Heer Software', '', 'Affiniteit met de zorg en sofwtare ontwikkeling. Help mee met de bouw van PCD en PCK', '3362TV')
,('Quality Equipment', '', 'Leuk jong bedrijf met frisse mensen en een leuk softwarepakket genaamd Q-7', '2984CD')
,('Dazzleware', '', 'Klein knus bedrijf dat software op maat levert', '1066EP')

insert into [dbo].[ContactPersons] (Name, Email, Employer_Id)
values('Jan Splinter', 'jsplinter@bar.com', 1)
,('Mieke van Oordrecht', 'mieke@foobar.com', 2)
,('Joost van der Gondel', 'jvg@bar.com', 3)
,('Thijs Visser', 'thijs@fb.com', 4)
,('Jeffrey van ''t Gooi', 'gooi@foobar.com', 5)
,('Laura Waterweg', 'lw@barfoo.com', 6)
,('Danielle Hoeverink', 'dh@barfoo@bar.com', 7)
,('Jantine Boer', 'boer@foob@barf.com', 8)

insert into zipcodes (value) values ('4205xp'), ('3362hb'), ('3363jd'), ('9121CB'), ('3365DB'), ('3362TV'), ('2984CD'), ('1066EP')

insert into Vacancies (Title, Description, HoursPerWeek, City, Zipcode_Id, SalaryFrom, SalaryTill, CreatedOn, ContactPerson_Id, Employer_Id, ThinkLevel_Id)
values ('Allround Storingsmonteur', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste velit atque dolore eos, est sed quaerat, non repellendus harum sint quod nam incidunt voluptas dolorem minima, placeat quae. Voluptatem, dignissimos!', 32, 'Sliedrecht', 3, 2800, 3200, GetDate(), 1, 1, 1)
,('Project Planner Offshore', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste velit atque dolore eos, est sed quaerat, non repellendus harum sint quod nam incidunt voluptas dolorem minima, placeat quae. Voluptatem, dignissimos!', 40, 'Sliedrecht', 2, 3200, 3500, GetDate(), 2, 2, 3)
,('Allround medewerker', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste velit atque dolore eos, est sed quaerat, non repellendus harum sint quod nam incidunt voluptas dolorem minima, placeat quae. Voluptatem, dignissimos!', 24, 'Gorinchem', 1, 2500, 2700, GetDate(), 3, 3, 2)
,('Medewerker Reisbureau', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste velit atque dolore eos, est sed quaerat, non repellendus harum sint quod nam incidunt voluptas dolorem minima, placeat quae. Voluptatem, dignissimos!', 32, 'Aalsum', 4, 2100, 2500, GetDate(), 4, 4, 1)
,('Customer Happiness Expert', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste velit atque dolore eos, est sed quaerat, non repellendus harum sint quod nam incidunt voluptas dolorem minima, placeat quae. Voluptatem, dignissimos!', 32, 'Papendrecht', 5, 2000, 2500, GetDate(), 5, 5, 2)
,('Receptioniste', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste velit atque dolore eos, est sed quaerat, non repellendus harum sint quod nam incidunt voluptas dolorem minima, placeat quae. Voluptatem, dignissimos!', 16, 'Sliedreht', 6, 1200, 1500, GetDate(), 6, 6, 1)
,('Medewerker Binnendienst', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste velit atque dolore eos, est sed quaerat, non repellendus harum sint quod nam incidunt voluptas dolorem minima, placeat quae. Voluptatem, dignissimos!', 32, 'Ridderkerk', 7, 2100, 2300, GetDate(), 7, 7, 2)
,('Projectmedewerker', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste velit atque dolore eos, est sed quaerat, non repellendus harum sint quod nam incidunt voluptas dolorem minima, placeat quae. Voluptatem, dignissimos!', 24, 'Amsterdam', 8, 2300, 2700, GetDate(), 8, 8, 2)

insert into [dbo].[Skills] (Name) 
values ('Aanpassingsvermogen'), ('Ambitieus'), ('Artistiek'), ('Analytisch vermogen'), ('Bemiddelen'), ('Behulpzaamheid'), ('Beoordelingsvermogen')
, ('Betrouwbaarheid'), ('Bondigheid'), ('Commercieel inzicht'), ('Concentratievermogen'), ('Contactuele vermogens'), ('Coöperatief')
, ('Coördinatietalent'), ('Delegeren'), ('Doelmatigheid'), ('Doorzettingsvermogen'), ('Enthousiasme'), ('Efficiënt werken'), ('Flexibiliteit')
, ('Geduld'), ('Gevoel voor cijfers'), ('Gevoel voor details'), ('Gevoel voor humor'), ('Handelsgeest'), ('Initiatiefnemend')
, ('Kostenbewust'), ('Kunstzinnig')
, ('Leergierig'), ('Leidinggevende capaciteiten'), ('Logisch denken'), ('Loyaliteit'), ('Luisteren'), ('Mensenkennis'), ('Omschakelingsvermogen')
, ('Onderhandelingsbekwaam'), ('Ondernemingszin'), ('Opmerkingsgave'), ('Optimisme'), ('Organisatietalent'), ('Overtuigingskracht')
, ('Perfectionisme'), ('Planmatig aanpakken')
, ('Praktische instelling'), ('Punctualiteit'), ('Relativeringsvermogen'), ('Schrijfvaardigheid'), ('Stabiliteit'), ('Spreekvaardigheid')
, ('Technisch inzicht'), ('Verbeeldingskracht'), ('Vindingrijkheid'), ('Zakelijk inzicht'), ('Zelfbeheersing'), ('Zelfmotivatie')
, ('Zelfstandig werkend'), ('Zelfvertrouwen')