insert into [dbo].[Skills] (Name) 
values ('Aanpassingsvermogen'), ('Ambitieus'), ('Artistiek'), ('Analytisch vermogen'), ('Bemiddelen'), ('Behulpzaamheid'), ('Beoordelingsvermogen')
, ('Betrouwbaarheid'), ('Bondigheid'), ('Commercieel inzicht'), ('Concentratievermogen'), ('Contactuele vermogens'), ('Coöperatief')
, ('Coördinatietalent'), ('Delegeren'), ('Doelmatigheid'), ('Doorzettingsvermogen'), ('Enthousiasme'), ('Efficiënt werken'), ('Flexibiliteit')
, ('Geduld'), ('Gevoel voor cijfers'), ('Gevoel voor details'), ('Gevoel voor humor'), ('Handelsgeest'), ('Initiatiefnemend')
, ('Kostenbewust'), ('Kunstzinnig')
, ('Leergierig'), ('Leidinggevende capaciteiten'), ('Logisch denken'), ('Loyaliteit'), ('Luisteren'), ('Mensenkennis'), ('Omschakelingsvermogen')
, ('Onderhandelingsbekwaam'), ('Ondernemingszin'), ('Opmerkingsgave'), ('Optimisme'), ('Organisatietalent'), ('Overtuigingskracht')
, ('Perfectionisme'), ('Planmatig aanpakken')
, ('Praktische instelling'), ('Punctualiteit'), ('Relativeringsvermogen'), ('Schrijfvaardigheid'), ('Stabiliteit'), ('Spreekvaardigheid')
, ('Technisch inzicht'), ('Verbeeldingskracht'), ('Vindingrijkheid'), ('Zakelijk inzicht'), ('Zelfbeheersing'), ('Zelfmotivatie')
, ('Zelfstandig werkend'), ('Zelfvertrouwen')